name: 'Upload a file'
description: 'Upload the given file'
inputs:
 environment:  # id of input
  description: Environment name
  required: true
  default: dev'
file-name:
 description: File Name
 required: true
 default: "upload"
  
outputs:
  file-name:
    description: "status of the action"
    value: ${{ steps.output-task.outputs.file-name }}
    
runs:
  using: "composite"  
  steps:
    - run: echo Hello ${{ inputs.environment }}
    
    - id: output-task
      name: output task      
      run: |
        file_name_ext="${{inputs.environment}}-${{inputs.file-name}}.txt"
        touch $file_name_ext
        echo "sample text" > $file_name_ext
        echo "::set-output name=file-name::$(echo ${{ inputs.file-name }})"     
        
    - name: Upload task
      uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.environment}}-${{inputs.file-name}}
          path: $file_name_ext
   
