name: Compoiste-Action-Consumer

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      environment: dev
      file-name: upload
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v3.0.0
       
      - name: Simple Step
        run: echo "Simple Test"
        
      - name: Composite-action
        uses: ./.github/workflows/composite-actions/upload
        id: composite-action
        with:
          environment: ${{ env.environment }}
          file-name: ${{ env.file-name }}
       
      - name: Ouput from Compiste ACtion
        run: |
          echo "Ouput from composite: ${{ steps.composite-action.outputs.file-name }}"
          
      - name: Download file (Uploaded from Composite)
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.environment }}-${{ steps.composite-action.outputs.file-name }}
          
      - name: Contents of File
        run: |
          cat  "${{ env.environment }}-${{ steps.composite-action.outputs.file-name }}.txt"
