name: curl test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
         response=$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' https://www.google.com)
         echo $response
        
