name: Checkout Gitlab Code and build



# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "getPegaPipelines"
  getPegaPipelines:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      run: |
        git clone https://oauth2:${{secrets.GITLAB_TOKEN}}@${{secrets.GITLAB_REPO_URL}}
        ls
    - name: Check npm version
      run: |  
        echo "Checking npm version"
        npm --version
        
    - name: Installing yarn
      run: |
        cd freecodecamp-gitlab-ci
        echo "Installing yarn"
        npm install -g yarn
        
    - name: Install yarn packages
      run: |
        cd freecodecamp-gitlab-ci
        echo "Install yarn packages"
        yarn install
        
    - name: Build App
      run: |
        cd freecodecamp-gitlab-ci
        echo "build app"
        yarn build
        
    - name: Run Tests
      run: |
        cd freecodecamp-gitlab-ci
        echo "Unit tests"
        yarn test
    
    - name: test
      run: |
        cd freecodecamp-gitlab-ci
        echo "test app"
        test -f build/index.html
   
        
    

