
name: "Jira-Trigger"

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:
    inputs:
      JIRA_ISSUE_KEY:
        description: "Jira Issue Decsription"
        required: true
      
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "getPegaPipelines"
  triggerPDMPipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Print the issue KEY
        run: |  
          echo ${{ inputs.JIRA_ISSUE_KEY }}
          
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get Jira Desciption Data
        id: jiraData
        uses: sudarsana-reddy/hello-world-javascript-action/custom-actions/jira-description-data@v1.1.2
        with:
          JIRA_REST_API_URL: ${{secrets.JIRA_REST_API_URL}}
          JIRA_ISSUE_KEY: ${{ inputs.JIRA_ISSUE_KEY }}
          JIRA_USERNAME: ${{ secrets.JIRA_USER_ID }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_APP_JSON_FILE: "jira-pega-apps.json" 

      - name: Upload jira app json file
        uses: actions/upload-artifact@v3
        with:         
          name: jira-pega-apps.json
          # A file, directory or wildcard pattern that describes what to upload
          path: jira-pega-apps.json

      - name: Trigger Pega Piplines
        uses: sudarsana-reddy/hello-world-javascript-action/custom-actions/trigger-pega-pipelines@v1.1.2
        with:
          PEGA_DM_REST_URL: ${{ secrets.PEGA_DM_REST_URL }}
          PEGA_DM_CLIENT_ID: ${{ secrets.PEGA_DM_CLIENT_ID }}
          PEGA_DM_CLIENT_SECRET: ${{ secrets.PEGA_DM_CLIENT_SECRET }}
          JIRA_PEGA_APP_DATA_JSON: "jira-pega-apps.json"
          PEGA_PIPELINE_MAPPING_JSON: "pega-pipilne-mappings.json"
      
