name: Job Status

on:
  workflow_dispatch:
  
 jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Job Status
        run: |
          echo "Status: ${{job.status}}"
          echo "Status: ${{job.conclusion}}"
