name: Job Status

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the step
        run: |
          exit 1;
      - name: Get Job Status
        if: failure()
        run: |
          echo "Status: ${{ job.status }}"
          
