name: curl test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
         response=$(curl http://www.google.com)
         echo $response
        
