# This is a basic workflow that is manually triggered

name: Sample Custom Action

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  custom-action:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    
    - name: Checkout custom action
      run: |      
        git clone -b dev https://${{ secrets.PAT }}@github.com/sudarsana-reddy/sample-gh-custom-action.git
        
    - name: echo the wokflow url
      uses: ./sample-gh-custom-action
      with:
        LOG_MESSAGE: "Sample"
        USERNAME: "SUD"
