name: Output Input

on: 
  workflow_dispatch:
    inputs:
      environment:      
        type: environment
        description: Select an environment
      
      testtype:
        type: choice
        description: Make a choice
        options:
          - dev
          - qa
          - sit
        

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output step
        run: |
          echo "my_name=sudarsan" >> $GITHUB_ENV
          
      - name: Echo Step output
        run: echo ${{ env.my_name }}
