name: "Pega Deployment -PDM Rest API"

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "getPegaPipelines"
  triggerPDMPipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2

    # Runs a single command using the runners shell
    - name: Trigger DM Pipeline
      env:
        PEGA_PIPELINE_ID: Pipeline-VGP8Q
      run: |
         echo "Running the Pega Script"
         bash pega.sh ${{secrets.PEGA_DM_REST_URL}} ${{secrets.PEGA_DM_CLIENT_ID}} ${{secrets.PEGA_DM_CLIENT_SECRET}} $PEGA_PIPELINE_ID TestProd15072022_1 01.01.02  
