name: Pega API workflow



# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  getPegaPipelines:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Get Pega DM Pipelines
      run: |
        echo "Running curl command"        
         
        curl_response = '$(curl --location --request POST "https://91dc-49-206-33-99.in.ngrok.io/prweb/PRRestService/oauth2/v1/token" \
                          --header "Content-Type: application/x-www-form-urlencoded" \
                          --header "Cookie: JSESSIONID=47ECE51670A6EB974930EC6B9BDE89F1" \
                          --data-urlencode "client_id=68656303360243191598" \
                          --data-urlencode "client_secret=5AE558DB2A7592EDF50B58C887191D9B" \
                          --data-urlencode "grant_type=client_credentials" )'
        
         echo "Running curl command - completed"     
        
        access_token = "$(echo $curl_response | jq -j '.access_token')   "
        echo "Access Token: $access_token"
        

