name: Powershell Test

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Run powershell script
        run: |
          pwsh ./p.ps1
