# This is a basic workflow that is manually triggered

name: prpcServiceUtils - Manual workflow

env: 
  PEGA_API_ASYNC: false
  PEGA_ARCHIVE_NAME: ${{inputs.PEGA_PROD_NAME}}.zip

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:
    inputs:
      PEGA_PROD_NAME:
        description: Pega Product rule name
        required: true
        
      PEGA_PROD_VERSION:
        description: Pega Product rule version
        required: true
        default: 01.01.01
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Hello ${{ github.event.inputs.name }}"        
        pwd 
        curl -o prpc87.zip https://d2xbzkyevnvl4b.cloudfront.net/prpcServiceUtils_8.7.zip
        unzip prpc87.zip -d prpc87           
        cd prpc87
        ls        
        cd scripts/utils
        echo "***********************Updating the file *****************************"
        echo ${{secrets.PEGA_URL}}
        sed -i -r "s#(pega.rest.server.url=)(.*)#\1${{secrets.PEGA_URL}}#" prpcServiceUtils.properties
        sed -i -r "s#(pega.rest.username=)(.*)#\1${{secrets.PEGA_USERNAME}}#" prpcServiceUtils.properties
        sed -i -r "s#(pega.rest.password=)(.*)#\1${{secrets.PEGA_PASSWORD}}#" prpcServiceUtils.properties
        sed -i -r "s#(pega.rest.response.type=)(.*)#\1${{secrets.PEGA_REST_RESPONSE_TYPE}}#" prpcServiceUtils.properties
        sed -i -r "s#(export.productVersion=)(.*)#\1${{inputs.PEGA_PROD_VERSION}}#" prpcServiceUtils.properties
        sed -i -r "s#(export.productName=)(.*)#\1${{inputs.PEGA_PROD_NAME}}#" prpcServiceUtils.properties
        sed -i -r "s#(export.async=)(.*)#\1${{env.PEGA_API_ASYNC}}#" prpcServiceUtils.properties       
         sed -i -r "s#(export.archiveName=)(.*)#\1${{env.PEGA_ARCHIVE_NAME}}#" prpcServiceUtils.properties
        echo "**********Updating the file completed***************"      
        mkdir artifacts
        ls
        chmod 711 ./../bin/ant        
        echo "^^^^^^^^^^^^^^^^^^^^^^^Staring the export^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
        bash ./prpcServiceUtils.sh export --propFile prpcServiceUtils.properties --artifactsDir ./artifacts
        ls
        cd artifacts
        ls
        cd ..
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: ${{inputs.PEGA_PROD_NAME}}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/prpc87/scripts/utils/artifacts/
       
  
        
        
