name: repo-secrets-reusable

on: 
  workflow_call:
    inputs:
      environment:
        description: "environment"
        default: test1
        required: true
        type: string
      env_token:
        description: "token"       
        required: true
        type: string
 
 jobs:
  test:
    runs-on: ubuntu-linux
    steps:
      - name: reusable 
        run: |  
          echo "Environment : ${{ inputs.environment }}"
           echo "token : ${{ inputs.env_token }}"
