name: repo-secrets-test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        default: test1
        
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.1
        
      - name: print the secrets
        run: |
          echo ${{ secrets['PEGA_URL'] }}
          echo ${{ vars['dev_url'] }}
          
        
  test:
    needs: checkout  
    uses: ./.github/workflows/repo-secrets-reusable.yml
    with:
       environment: ${{ inputs.environment }}
       url: ${{ vars['dev_url'] }}
    secrets:
       env_token: ${{ secrets.test1_token }}
