name: repo-secrets-test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        default: test1
        
jobs:
  test:
    runs-on: ubuntu-linux
    steps:
      - name: test the value
        run: |  
          echo ${{ secrets.test1_token }}
          echo ${{ secrets.test2_token }}
          echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
          environment_token=${{inputs.environment}}_token
          echo ${{ secrets."$environment_token" }}
