name: repo-secrets-test

on: 
  workflow_dispatch:
    inputs:
      environment:
        descriptiom: "environment"
        deafut: test1
        
jobs:
  test:
    runs-on: ubuntu-linux
    steps:
      - name: test the value
        run: |  
          echo ${{ secrets.test1_token }}
          echo ${{ secrets.test2_token }}
          echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
          echo ${{ secrets.${{inputs.environment}}_token }}
          
  
      
  
