name: repo-secrets-test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        default: test1
        
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.1
        
  test:
    needs: checkout  
    uses: ./.github/workflows/repo-secrets-reusable.yml
    with:
       environment: ${{ inputs.environment }}
       env_token: ${{ secrets.test1_token }}
