name: repo-secrets-test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        default: test1        
        
jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      DEV_URL: ${{ steps.initVars.outputs.DEV_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.1
          
      - name: initVars
        run: |
          echo "DEV_URL=abcdefgh" >> $GITHUB_OUTPUT
          
      - name: print the secrets
        run: |
          echo ${{ secrets['PEGA_URL'] }}
          echo  "${{ steps.initVars.outputs.DEV_URL }}"
          
        
  test:
    needs: checkout  
    uses: ./.github/workflows/repo-secrets-reusable.yml
    with:
       environment: ${{ inputs.environment }}
       url: ${{ needs.checkout.outputs.DEV_URL }}
    secrets:
       env_token: ${{ secrets.test1_token }}
