name: repo-secrets-test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        default: test1
        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test the value
        uses: ./.github/workflows/repo-secrets-reusable.yml
        with:
          environment: ${{ inputs.environment }}
          env_token: ${{ secrets.test1_token }}
