name: repo-secrets-reusable

on: 
  workflow_call:
    inputs:
      environment:
        description: "environment"      
        required: true
        type: string
      url:
        description: "url"      
        required: true
        type: string
    secrets:
      env_token:
        description: "token"       
        required: true       
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: reusable 
        run: |  
          echo "Environment : ${{ inputs.environment }}"
           echo "token : ${{ secrets.env_token }}"
           echo "variables: ${{ inputs.url }}"
