name: Remote Trigger Flow

on: 
  workflow_dispatch:
    inputs:
#       PDM parameters
      DeploymentID:
        description: "Deployment ID of the pipeline on which the task is triggered" 
        required: true      
      DeploymentNumber:
        description: "Sequence number of the deployment."
        required: true
      CallBackURL:
        description: "Pega Callback URL"
        required: true
      TaskID:
        description: "TaskID of the GitHub task"
        required: true       
      OrchestratorURL:
        description: "URL on which the GitHub task is configured"
        required: true
      PipelineName:
        description: "Pipeline name on which the GitHub task is configured"
        required: true        
      PipelineID:
        description: "ID of the pipeline on which the GitHub task is configured"
        required: true       
      CurrentStage:
        description: "Name of the stage on which the GitHub task is configured"
        required: true
      CurrentStageURL:
        description: "URL of the system on which the GitHub task is configured"
        required: true
      DeploymentArtifactName:
        description: "Artifact name that the Deploy task uses on the stage on which the GitHub task is configured"
        required: false
      ArtifactPath:
        description: "Full path to the artifact that the Deploy task uses"
        required: false
#       Workflow parameters
      TEST_SUITE_NAME:
        description: "Automation test suite (testng xml) to be executed"
        required: true

jobs:
  pega-github-custom-task:   
    runs-on: ubuntu-latest
    steps:
    - name: Print all the parameters
      run: |   
        echo "DeploymentID: ${{ inputs.DeploymentID }}"
        echo "DeploymentNumber: ${{ inputs.DeploymentNumber }}"
        echo "CallBackURL: ${{ inputs.CallBackURL }}"
        echo "TaskID: ${{ inputs.TaskID }}"
        echo "OrchestratorURL: ${{ inputs.OrchestratorURL }}"
        echo "PipelineName: ${{ inputs.PipelineName }}"
        echo "PipelineID: ${{ inputs.PipelineID }}"
        echo "CurrentStage: ${{ inputs.CurrentStage }}"
        echo "CurrentStageURL: ${{ inputs.CurrentStageURL }}"
        echo "DeploymentArtifactName: ${{ inputs.DeploymentArtifactName }}"
        echo "ArtifactPath: ${{ inputs.ArtifactPath }}"
        echo "TEST_SUITE_NAME: ${{ inputs.TEST_SUITE_NAME }}"       
