name: Remote Trigger Flow

on: 
  workflow_dispatch:
    inputs:
      FILE1:
        description: File Name 
        required: true
        default: a.txt
      param2:
        description: "demo file"
        required: true
      callbackURL:
        description: "Pega Callback URL"
        required: false
      

env:
  FILE2: b.txt
  ENVIRONMENT_FILE: a.properties
  ENVIRONMENT: dev

jobs:
  add2Files:   
    runs-on: ubuntu-latest
    steps:
    - name: Create 2 Files
      run: |   
      
        if [[ ! -z "${{ inputs.callbackURL }}" ]]
        then
          echo ${{ inputs.callbackURL }}
          user2_response=$(curl --location ${{ inputs.callbackURL}})
          echo $user2_response
        else
          echo "no callback url passed"
        fi       
        
        echo "Creating 2 Files"
        touch ${{inputs.FILE1}}
        echo "first file" >> ${{inputs.FILE1}}
        touch ${{env.FILE2}}
        echo "second file" >> ${{env.FILE2}}
        echo "environment=${{env.ENVIRONMENT}}" >> ${{env.ENVIRONMENT_FILE}}
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
         name: homework
         path: |
           a.txt
           b.txt
           ${{env.ENVIRONMENT_FILE}}
