name: Scheduler TestFlow

on: 
  workflow_dispatch:
    inputs:
      FILE1:
        description: File Name 
        required: true
        default: nothing

env:
#   FILE1: a.txt
  FILE2: b.txt
  ENVIRONMENT_FILE: a.properties
  ENVIRONMENT: dev

jobs:
  add2Files:   
    runs-on: ubuntu-latest
    steps:
    - name: Create 2 Files
      run: |
        echo "Creating 2 Files"
        touch ${{env.FILE1}}
        echo "first file" >> ${{inputs.FILE1}}
        touch ${{env.FILE2}}
        echo "second file" >> ${{env.FILE2}}
        echo "environment=${{env.ENVIRONMENT}}" >> ${{env.ENVIRONMENT_FILE}}
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
         name: homework
         path: |
           a.txt
           b.txt
           ${{env.ENVIRONMENT_FILE}}
